apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: node-agent-cluster-resources
rules:
- apiGroups:
  - ""
  - batch
  - power.cluster-power-manager.github.io
  resources:
  - nodes
  - nodes/status
  - pods
  - pods/status
  - powernodeconfigs
  - powerprofiles
  - powerprofiles/status
  - powernodestates
  - powernodestates/status
  - uncores
  - uncores/status
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
