apiVersion: power.cluster-power-manager.github.io/v1alpha1
kind: PowerConfig
metadata:
  labels:
    app.kubernetes.io/name: PowerConfig
    app.kubernetes.io/instance: power-config
    app.kubernetes.io/part-of: kubernetes-power-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-power-manager
  name: power-config
  namespace: power-manager
spec:
  powerNodeSelector:
    # Add labels here for the Nodes you want the PowerNodeAgent to be applied to
    feature.node.kubernetes.io/power-node: "true"
