apiVersion: power.cluster-power-manager.github.io/v1alpha1
kind: PowerNodeConfig
metadata:
  name: amd64-config
  namespace: power-manager
spec:
  sharedPowerProfile: amd64-shared
  nodeSelector:
    labelSelector:
      matchLabels:
        kubernetes.io/arch: amd64
  reservedCPUs:
  - cores:
    - 0
    - 1
    - 24
    - 25
    powerProfile: amd64-performance
