//go:build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUPoolsStatus) DeepCopyInto(out *CPUPoolsStatus) {
	*out = *in
	if in.Shared != nil {
		in, out := &in.Shared, &out.Shared
		*out = new(SharedCPUPoolStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Reserved != nil {
		in, out := &in.Reserved, &out.Reserved
		*out = make([]ReservedCPUPoolStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Exclusive != nil {
		in, out := &in.Exclusive, &out.Exclusive
		*out = make([]ExclusiveCPUPoolStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUPoolsStatus.
func (in *CPUPoolsStatus) DeepCopy() *CPUPoolsStatus {
	if in == nil {
		return nil
	}
	out := new(CPUPoolsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CStatesConfig) DeepCopyInto(out *CStatesConfig) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MaxLatencyUs != nil {
		in, out := &in.MaxLatencyUs, &out.MaxLatencyUs
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CStatesConfig.
func (in *CStatesConfig) DeepCopy() *CStatesConfig {
	if in == nil {
		return nil
	}
	out := new(CStatesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Container) DeepCopyInto(out *Container) {
	*out = *in
	if in.ExclusiveCPUs != nil {
		in, out := &in.ExclusiveCPUs, &out.ExclusiveCPUs
		*out = make([]uint, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Container.
func (in *Container) DeepCopy() *Container {
	if in == nil {
		return nil
	}
	out := new(Container)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CpuScalingPolicy) DeepCopyInto(out *CpuScalingPolicy) {
	*out = *in
	if in.SamplePeriod != nil {
		in, out := &in.SamplePeriod, &out.SamplePeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.CooldownPeriod != nil {
		in, out := &in.CooldownPeriod, &out.CooldownPeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.TargetUsage != nil {
		in, out := &in.TargetUsage, &out.TargetUsage
		*out = new(int)
		**out = **in
	}
	if in.AllowedUsageDifference != nil {
		in, out := &in.AllowedUsageDifference, &out.AllowedUsageDifference
		*out = new(int)
		**out = **in
	}
	if in.AllowedFrequencyDifference != nil {
		in, out := &in.AllowedFrequencyDifference, &out.AllowedFrequencyDifference
		*out = new(int)
		**out = **in
	}
	if in.ScalePercentage != nil {
		in, out := &in.ScalePercentage, &out.ScalePercentage
		*out = new(int)
		**out = **in
	}
	if in.FallbackFreqPercent != nil {
		in, out := &in.FallbackFreqPercent, &out.FallbackFreqPercent
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CpuScalingPolicy.
func (in *CpuScalingPolicy) DeepCopy() *CpuScalingPolicy {
	if in == nil {
		return nil
	}
	out := new(CpuScalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DieSelector) DeepCopyInto(out *DieSelector) {
	*out = *in
	if in.Package != nil {
		in, out := &in.Package, &out.Package
		*out = new(uint)
		**out = **in
	}
	if in.Die != nil {
		in, out := &in.Die, &out.Die
		*out = new(uint)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(uint)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(uint)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DieSelector.
func (in *DieSelector) DeepCopy() *DieSelector {
	if in == nil {
		return nil
	}
	out := new(DieSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExclusiveCPUPoolStatus) DeepCopyInto(out *ExclusiveCPUPoolStatus) {
	*out = *in
	if in.PowerContainers != nil {
		in, out := &in.PowerContainers, &out.PowerContainers
		*out = make([]PowerContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExclusiveCPUPoolStatus.
func (in *ExclusiveCPUPoolStatus) DeepCopy() *ExclusiveCPUPoolStatus {
	if in == nil {
		return nil
	}
	out := new(ExclusiveCPUPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuaranteedPod) DeepCopyInto(out *GuaranteedPod) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuaranteedPod.
func (in *GuaranteedPod) DeepCopy() *GuaranteedPod {
	if in == nil {
		return nil
	}
	out := new(GuaranteedPod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeInfo) DeepCopyInto(out *NodeInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeInfo.
func (in *NodeInfo) DeepCopy() *NodeInfo {
	if in == nil {
		return nil
	}
	out := new(NodeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSelector) DeepCopyInto(out *NodeSelector) {
	*out = *in
	in.LabelSelector.DeepCopyInto(&out.LabelSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSelector.
func (in *NodeSelector) DeepCopy() *NodeSelector {
	if in == nil {
		return nil
	}
	out := new(NodeSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeUncoreStatus) DeepCopyInto(out *NodeUncoreStatus) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeUncoreStatus.
func (in *NodeUncoreStatus) DeepCopy() *NodeUncoreStatus {
	if in == nil {
		return nil
	}
	out := new(NodeUncoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PStatesConfig) DeepCopyInto(out *PStatesConfig) {
	*out = *in
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PStatesConfig.
func (in *PStatesConfig) DeepCopy() *PStatesConfig {
	if in == nil {
		return nil
	}
	out := new(PStatesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerConfig) DeepCopyInto(out *PowerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerConfig.
func (in *PowerConfig) DeepCopy() *PowerConfig {
	if in == nil {
		return nil
	}
	out := new(PowerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerConfigList) DeepCopyInto(out *PowerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerConfigList.
func (in *PowerConfigList) DeepCopy() *PowerConfigList {
	if in == nil {
		return nil
	}
	out := new(PowerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerConfigSpec) DeepCopyInto(out *PowerConfigSpec) {
	*out = *in
	if in.PowerNodeSelector != nil {
		in, out := &in.PowerNodeSelector, &out.PowerNodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerConfigSpec.
func (in *PowerConfigSpec) DeepCopy() *PowerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PowerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerConfigStatus) DeepCopyInto(out *PowerConfigStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.StatusErrors.DeepCopyInto(&out.StatusErrors)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerConfigStatus.
func (in *PowerConfigStatus) DeepCopy() *PowerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(PowerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerContainer) DeepCopyInto(out *PowerContainer) {
	*out = *in
	if in.CPUIDs != nil {
		in, out := &in.CPUIDs, &out.CPUIDs
		*out = make([]uint, len(*in))
		copy(*out, *in)
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerContainer.
func (in *PowerContainer) DeepCopy() *PowerContainer {
	if in == nil {
		return nil
	}
	out := new(PowerContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerNodeConfig) DeepCopyInto(out *PowerNodeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerNodeConfig.
func (in *PowerNodeConfig) DeepCopy() *PowerNodeConfig {
	if in == nil {
		return nil
	}
	out := new(PowerNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerNodeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerNodeConfigList) DeepCopyInto(out *PowerNodeConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerNodeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerNodeConfigList.
func (in *PowerNodeConfigList) DeepCopy() *PowerNodeConfigList {
	if in == nil {
		return nil
	}
	out := new(PowerNodeConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerNodeConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerNodeConfigSpec) DeepCopyInto(out *PowerNodeConfigSpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	if in.ReservedCPUs != nil {
		in, out := &in.ReservedCPUs, &out.ReservedCPUs
		*out = make([]ReservedSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerNodeConfigSpec.
func (in *PowerNodeConfigSpec) DeepCopy() *PowerNodeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PowerNodeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerNodeConfigStatus) DeepCopyInto(out *PowerNodeConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerNodeConfigStatus.
func (in *PowerNodeConfigStatus) DeepCopy() *PowerNodeConfigStatus {
	if in == nil {
		return nil
	}
	out := new(PowerNodeConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerNodeProfileStatus) DeepCopyInto(out *PowerNodeProfileStatus) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerNodeProfileStatus.
func (in *PowerNodeProfileStatus) DeepCopy() *PowerNodeProfileStatus {
	if in == nil {
		return nil
	}
	out := new(PowerNodeProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerNodeState) DeepCopyInto(out *PowerNodeState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerNodeState.
func (in *PowerNodeState) DeepCopy() *PowerNodeState {
	if in == nil {
		return nil
	}
	out := new(PowerNodeState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerNodeState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerNodeStateList) DeepCopyInto(out *PowerNodeStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerNodeState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerNodeStateList.
func (in *PowerNodeStateList) DeepCopy() *PowerNodeStateList {
	if in == nil {
		return nil
	}
	out := new(PowerNodeStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerNodeStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerNodeStateSpec) DeepCopyInto(out *PowerNodeStateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerNodeStateSpec.
func (in *PowerNodeStateSpec) DeepCopy() *PowerNodeStateSpec {
	if in == nil {
		return nil
	}
	out := new(PowerNodeStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerNodeStateStatus) DeepCopyInto(out *PowerNodeStateStatus) {
	*out = *in
	if in.NodeInfo != nil {
		in, out := &in.NodeInfo, &out.NodeInfo
		*out = new(NodeInfo)
		**out = **in
	}
	if in.PowerProfiles != nil {
		in, out := &in.PowerProfiles, &out.PowerProfiles
		*out = make([]PowerNodeProfileStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CPUPools != nil {
		in, out := &in.CPUPools, &out.CPUPools
		*out = new(CPUPoolsStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Uncore != nil {
		in, out := &in.Uncore, &out.Uncore
		*out = new(NodeUncoreStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerNodeStateStatus.
func (in *PowerNodeStateStatus) DeepCopy() *PowerNodeStateStatus {
	if in == nil {
		return nil
	}
	out := new(PowerNodeStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerProfile) DeepCopyInto(out *PowerProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerProfile.
func (in *PowerProfile) DeepCopy() *PowerProfile {
	if in == nil {
		return nil
	}
	out := new(PowerProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerProfileCPUs) DeepCopyInto(out *PowerProfileCPUs) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerProfileCPUs.
func (in *PowerProfileCPUs) DeepCopy() *PowerProfileCPUs {
	if in == nil {
		return nil
	}
	out := new(PowerProfileCPUs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerProfileList) DeepCopyInto(out *PowerProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerProfileList.
func (in *PowerProfileList) DeepCopy() *PowerProfileList {
	if in == nil {
		return nil
	}
	out := new(PowerProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerProfileSpec) DeepCopyInto(out *PowerProfileSpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	in.PStates.DeepCopyInto(&out.PStates)
	in.CStates.DeepCopyInto(&out.CStates)
	out.CpuCapacity = in.CpuCapacity
	if in.CpuScalingPolicy != nil {
		in, out := &in.CpuScalingPolicy, &out.CpuScalingPolicy
		*out = new(CpuScalingPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerProfileSpec.
func (in *PowerProfileSpec) DeepCopy() *PowerProfileSpec {
	if in == nil {
		return nil
	}
	out := new(PowerProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerProfileStatus) DeepCopyInto(out *PowerProfileStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerProfileStatus.
func (in *PowerProfileStatus) DeepCopy() *PowerProfileStatus {
	if in == nil {
		return nil
	}
	out := new(PowerProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservedCPUPoolStatus) DeepCopyInto(out *ReservedCPUPoolStatus) {
	*out = *in
	if in.PowerProfileCPUs != nil {
		in, out := &in.PowerProfileCPUs, &out.PowerProfileCPUs
		*out = make([]PowerProfileCPUs, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservedCPUPoolStatus.
func (in *ReservedCPUPoolStatus) DeepCopy() *ReservedCPUPoolStatus {
	if in == nil {
		return nil
	}
	out := new(ReservedCPUPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservedSpec) DeepCopyInto(out *ReservedSpec) {
	*out = *in
	if in.Cores != nil {
		in, out := &in.Cores, &out.Cores
		*out = make([]uint, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservedSpec.
func (in *ReservedSpec) DeepCopy() *ReservedSpec {
	if in == nil {
		return nil
	}
	out := new(ReservedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedCPUPoolStatus) DeepCopyInto(out *SharedCPUPoolStatus) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedCPUPoolStatus.
func (in *SharedCPUPoolStatus) DeepCopy() *SharedCPUPoolStatus {
	if in == nil {
		return nil
	}
	out := new(SharedCPUPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusErrors) DeepCopyInto(out *StatusErrors) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusErrors.
func (in *StatusErrors) DeepCopy() *StatusErrors {
	if in == nil {
		return nil
	}
	out := new(StatusErrors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Uncore) DeepCopyInto(out *Uncore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Uncore.
func (in *Uncore) DeepCopy() *Uncore {
	if in == nil {
		return nil
	}
	out := new(Uncore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Uncore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UncoreList) DeepCopyInto(out *UncoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Uncore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UncoreList.
func (in *UncoreList) DeepCopy() *UncoreList {
	if in == nil {
		return nil
	}
	out := new(UncoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UncoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UncoreSpec) DeepCopyInto(out *UncoreSpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	if in.SysMax != nil {
		in, out := &in.SysMax, &out.SysMax
		*out = new(uint)
		**out = **in
	}
	if in.SysMin != nil {
		in, out := &in.SysMin, &out.SysMin
		*out = new(uint)
		**out = **in
	}
	if in.DieSelectors != nil {
		in, out := &in.DieSelectors, &out.DieSelectors
		*out = new([]DieSelector)
		if **in != nil {
			in, out := *in, *out
			*out = make([]DieSelector, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UncoreSpec.
func (in *UncoreSpec) DeepCopy() *UncoreSpec {
	if in == nil {
		return nil
	}
	out := new(UncoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UncoreStatus) DeepCopyInto(out *UncoreStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UncoreStatus.
func (in *UncoreStatus) DeepCopy() *UncoreStatus {
	if in == nil {
		return nil
	}
	out := new(UncoreStatus)
	in.DeepCopyInto(out)
	return out
}
