apiVersion: power.cluster-power-manager.github.io/v1alpha1
kind: PowerProfile
metadata:
  name: shared
  namespace: power-manager
spec:
  shared: true
  pstates:
    max: 1000
    min: 1000
    epp: "power"
    governor: "powersave"
  cstates:
    # Configure C-states using either 'maxLatencyUs' or 'names', but not both
    maxLatencyUs: 1
    #names:
    #  C1: true
    #  C6: false
